"""
Healer Agent - Fix Generation.

This agent is responsible for:
1. Generating code fixes based on bug analysis
2. Producing multiple fix candidates
3. Providing explanations for each fix
4. Estimating fix confidence

Uses GPT-4 for creative code generation.

Author: Millicent Mufambi (H240624A)
"""

from dataclasses import dataclass
from typing import Optional, List
from datetime import datetime
import json
import re

from app.agents.base_agent import BaseAgent, AgentConfig, AgentOutput, AgentType, LLMProvider
from app.agents.analyzer_agent import BugAnalysisResult
import structlog

logger = structlog.get_logger(__name__)


@dataclass
class FixGenerationInput:
    """Input for fix generation."""
    bug_analysis: BugAnalysisResult
    original_code: str
    file_path: str
    line_number: int
    language: str
    additional_context: Optional[str] = None


@dataclass
class FixCandidate:
    """A candidate fix generated by the healer."""
    fixed_code: str
    explanation: str
    confidence: float
    changes_description: str
    potential_side_effects: List[str]


@dataclass
class FixGenerationResult:
    """Result of fix generation."""
    candidates: List[FixCandidate]
    recommended_index: int
    generation_strategy: str


class HealerAgent(BaseAgent):
    """
    Healer Agent for generating code fixes.

    This agent specializes in generating fix candidates for identified bugs.
    It produces multiple alternatives with different approaches and
    confidence levels for the consensus process.

    Typically uses GPT-4 for its strong code generation capabilities.
    """

    def __init__(self, config: Optional[AgentConfig] = None):
        if config is None:
            config = AgentConfig(
                agent_id="healer-gpt4-01",
                agent_type=AgentType.HEALER,
                llm_provider=LLMProvider.GPT4,
                model_name="gpt-4",
                temperature=0.7,  # Higher temperature for creative fixes
                max_tokens=2048,
            )
        super().__init__(config)

    async def process(self, input_data: FixGenerationInput) -> AgentOutput:
        """
        Generate fix candidates for a bug.

        Args:
            input_data: Bug analysis and code context

        Returns:
            AgentOutput containing FixGenerationResult
        """
        start_time = datetime.utcnow()

        try:
            prompt = self._build_prompt(input_data)
            llm_response = await self._call_llm(prompt)
            result = self._parse_response(llm_response, input_data)

            latency = (datetime.utcnow() - start_time).total_seconds() * 1000

            self.update_reputation(True)

            logger.info(
                "Fixes generated",
                agent_id=self.agent_id,
                num_candidates=len(result.candidates),
                recommended=result.recommended_index,
                latency_ms=latency
            )

            return AgentOutput(
                agent_id=self.agent_id,
                agent_type=self.agent_type,
                success=True,
                result=result,
                confidence=result.candidates[result.recommended_index].confidence if result.candidates else 0.0,
                reasoning=result.generation_strategy,
                latency_ms=latency,
                metadata={
                    "num_candidates": len(result.candidates),
                    "strategy": result.generation_strategy,
                }
            )

        except Exception as e:
            latency = (datetime.utcnow() - start_time).total_seconds() * 1000
            self.update_reputation(False)

            logger.error("Fix generation failed", error=str(e))

            return AgentOutput(
                agent_id=self.agent_id,
                agent_type=self.agent_type,
                success=False,
                result=None,
                confidence=0.0,
                reasoning=f"Generation failed: {str(e)}",
                latency_ms=latency,
            )

    def _build_prompt(self, input_data: FixGenerationInput) -> str:
        """Build the fix generation prompt for the LLM."""
        return f"""You are an expert software engineer fixing a bug in production code.
Generate multiple fix candidates for the following bug.

## Bug Analysis
**Type:** {input_data.bug_analysis.bug_type}
**Severity:** {input_data.bug_analysis.severity}
**Root Cause:** {input_data.bug_analysis.root_cause}
**Suggested Approach:** {input_data.bug_analysis.suggested_approach}

## Original Code
**File:** {input_data.file_path}
**Line:** {input_data.line_number}
**Language:** {input_data.language}

```{input_data.language}
{input_data.original_code}
```

## Your Task
Generate 2-3 different fix candidates. For each fix:
1. Provide the complete fixed code
2. Explain what was changed and why
3. Estimate confidence (0.0-1.0)
4. List potential side effects

Respond with a JSON object:
{{
    "candidates": [
        {{
            "fixed_code": "<complete fixed code>",
            "explanation": "<what was changed and why>",
            "confidence": <0.0-1.0>,
            "changes_description": "<brief description of changes>",
            "potential_side_effects": ["<list of potential issues>"]
        }}
    ],
    "recommended_index": <index of best candidate>,
    "generation_strategy": "<brief description of approach>"
}}

Important:
- Preserve the original code structure
- Only fix the actual bug, don't refactor
- Ensure the fix is safe for production
- Consider edge cases

Respond ONLY with the JSON object."""

    def _parse_response(
        self,
        response: str,
        input_data: FixGenerationInput
    ) -> FixGenerationResult:
        """Parse the LLM response into structured results."""
        # Extract JSON from response
        json_match = re.search(r'\{.*\}', response, re.DOTALL)
        if json_match:
            response = json_match.group()

        try:
            data = json.loads(response)
        except json.JSONDecodeError:
            # Fallback: create a single minimal fix candidate
            return FixGenerationResult(
                candidates=[
                    FixCandidate(
                        fixed_code=input_data.original_code,
                        explanation="Unable to generate fix automatically",
                        confidence=0.1,
                        changes_description="No changes made",
                        potential_side_effects=["Manual review required"]
                    )
                ],
                recommended_index=0,
                generation_strategy="fallback"
            )

        candidates = []
        for c in data.get("candidates", []):
            candidates.append(FixCandidate(
                fixed_code=c.get("fixed_code", input_data.original_code),
                explanation=c.get("explanation", ""),
                confidence=float(c.get("confidence", 0.5)),
                changes_description=c.get("changes_description", ""),
                potential_side_effects=c.get("potential_side_effects", [])
            ))

        if not candidates:
            candidates = [
                FixCandidate(
                    fixed_code=input_data.original_code,
                    explanation="No fix generated",
                    confidence=0.0,
                    changes_description="",
                    potential_side_effects=[]
                )
            ]

        return FixGenerationResult(
            candidates=candidates,
            recommended_index=min(
                data.get("recommended_index", 0),
                len(candidates) - 1
            ),
            generation_strategy=data.get("generation_strategy", "llm_generation")
        )
